version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    environment:
      - PORT=3333
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - secure-vault-net
    ports:
      - "3333:3333"
    restart: always

  # Frontend Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:80"
    depends_on:
      - backend
    networks:
      - secure-vault-net
    restart: always

networks:
  secure-vault-net:
    driver: bridge
